# Generated by Django 3.1.7 on 2021-04-16 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0003_auto_20210416_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProductsApp.categories'),
            preserve_default=False,
        ),
    ]
