# Generated by Django 3.1.7 on 2021-04-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0005_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avatar', models.ImageField(upload_to='images/products/brands')),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
    ]
