# Generated by Django 3.1.7 on 2021-04-21 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0010_shop_merchant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
