# Generated by Django 3.1.7 on 2021-04-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0012_auto_20210421_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='subcategories_id',
        ),
        migrations.DeleteModel(
            name='SubCategories',
        ),
    ]
