# Generated by Django 3.1.7 on 2021-04-26 17:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0016_auto_20210425_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_long_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
