# Generated by Django 3.1.7 on 2021-05-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0020_emailsubscibers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSubscibers',
        ),
    ]
