# Generated by Django 3.1.7 on 2021-05-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0022_compaireitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
