# Generated by Django 3.1.7 on 2021-05-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0023_products_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ProductsApp.Tags'),
        ),
        migrations.AddField(
            model_name='tags',
            name='show_index',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ProductTags',
        ),
    ]
