# Generated by Django 3.1.7 on 2021-05-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0024_auto_20210506_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='show_index',
            new_name='show_on_index',
        ),
    ]
