# Generated by Django 3.1.7 on 2021-05-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0025_auto_20210506_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmedia',
            name='media_type',
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='media_content',
            field=models.ImageField(upload_to='images/products/product_media'),
        ),
    ]
