# Generated by Django 3.1.7 on 2021-05-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0026_auto_20210506_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='brief_describtion',
            field=models.CharField(default='Lets describe', max_length=70),
            preserve_default=False,
        ),
    ]
