# Generated by Django 3.2.2 on 2021-08-06 18:48

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('ProductsApp', '0028_alter_products_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
