# Generated by Django 3.1.7 on 2021-04-22 07:04

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210421_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogmedia',
            name='post_file',
        ),
        migrations.AddField(
            model_name='blogmedia',
            name='post_image',
            field=models.ImageField(default=1, upload_to='images/blog/detail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
