# Generated by Django 3.1.7 on 2021-04-20 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_phonenumber_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='date_added',
        ),
    ]
