# Generated by Django 3.1.7 on 2021-04-20 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_phonenumber_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
