# Generated by Django 3.1.7 on 2021-04-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_phonenumber_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'AdminUser'), (2, 'StaffUser'), (3, 'MerchantUser'), (4, 'CustomerUser')], default=1, max_length=255),
        ),
    ]
