# Generated by Django 3.1.7 on 2021-04-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20210421_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminuser',
            old_name='auth_user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='customeruser',
            old_name='auth_user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='merchantuser',
            old_name='auth_user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='staffuser',
            old_name='auth_user_id',
            new_name='user',
        ),
    ]
