# Generated by Django 3.1.7 on 2021-05-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_emailsubscibers'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='google_plus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='linked_in',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='list_on_about',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
