# Generated by Django 3.1.7 on 2021-05-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_staffuser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='position',
            field=models.CharField(choices=[('CEO', 'CEO'), ('Marketing Officer', 'Marketing Officer'), ('Customer Care', 'Customer Care'), ('Quality Officer', 'Quality Officer')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
