# Generated by Django 3.2.2 on 2021-08-05 17:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_bestcustomerreviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestcustomerreviews',
            options={'verbose_name': 'Best Customer Review', 'verbose_name_plural': 'Best Customer Reviews'},
        ),
        migrations.AddField(
            model_name='bestcustomerreviews',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 8, 5, 17, 36, 16, 546194, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='images/profile/default-profile.jpg', upload_to='images/profile/customer'),
        ),
    ]
